# Relatório de Estatistica Aplicada - 3° Estágio

Alunos: 
- André Tharssys Marques Soares
- Vinicius de Oliveira Porto

## Questão 01

### Escreva em linhas gerais sobre o que será analisado através dos dados

De forma geral, a análise da tabela “Índice de Satisfação de Clientes” permitirá compreender como diferentes fatores, como perfil do cliente, tempo de espera, tempo de resposta, preço pago, resolutividade do atendimento e canal utilizado, influenciam a percepção de qualidade, os índices de satisfação (NPS e ISC) e a experiência geral do cliente, possibilitando a identificação de pontos fortes e de aspectos que contribuem para a insatisfação.

## Questão 02

 ### Descreva a base de dados indicando o número de observações e as variáveis com os “names”, seus significados e as correspondentes unidades de medida

In [9]:
import pandas as pd

In [23]:
# Criando um DateFrame com os dados da tabela

df_SatisfacaoCliente = pd.read_csv(r"C:\Projetos\UFCG\relatorio_estatisitica\atv_estagio03_estatisticaAplicada\Indice_de_satisfação_de_clientes.xlsx-Sheet1.csv")

In [19]:
df_SatisfacaoCliente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1997 entries, 0 to 1996
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   tipo_servico            1997 non-null   object
 1   canal_atendimento       1997 non-null   object
 2   faixa_etaria            1997 non-null   object
 3   tempo_espera            1987 non-null   object
 4   qualidade_percebida     1987 non-null   object
 5   preco_pago              1987 non-null   object
 6   atendimento_resolutivo  1997 non-null   object
 7   nps                     1997 non-null   object
 8   tempo_resposta          1997 non-null   object
 9   isc                     1997 non-null   object
dtypes: object(10)
memory usage: 156.1+ KB

Base de dados:
- Número de observações(linhas): 1997
- Número de variáveis(colunas): 10

Variáveis:
- tipo_servico: Corresponde ao tipo de serviço contratado/prestado ao cliente, é uma unidade do tipo qualitativo categórica 
- canal_atendimento: Corresponde ao meio de contato utilizado pelo cliente, é uma unidade do tipo qualitativo categórica
- faixa_etaria: Corresponde a faixa de idade do cliente, é uma unidade do tipo qualitativa ordinal
- tempo_espera: Corresponde ao tempo esperado pelo cliente para ser atendido, é uma unidade do tipo quantitativa contínua (em minutos)
- qualidade_percebida: Corresponde a um valor de avaliação do cliente pelo atendimento recebido, é uma unidade quantitativa contínua de 0 a 10
- preco_pago: Corresponde ao valor pago pelo cliente pelo serviço prestado, é uma unidade do tipo quantitativa contínua (em reais)
- atendimento_resolutivo: Corresponde a uma resposta se um atendimento resolveu ou não a questão do cliente, é uma unidade qualitativa binária (pode ser tratado como boolean)
- nps: Corresponde am um indice de lealdade do cliente, ou seja, uma probabilidade do cliente recomendar esse serviço, é uma unidade quantitativa contínua de 0 a 10
- tempo_resposta: Corresponde ao tempo que a empresa levou para atender o cliente, é uma unidade do tipo quantitativa contínua (em minutos)
- isc: Corresponde a um indicador de satisfação geral do cliente, é uma unidade do tipo quantitativa contínua (em percentual)

## Questão 03

### Apresente uma boa análise exploratória de dados sempre visando identificar possíveis ausências de dados, “outliers”, bem como responder às questões/objetivos da pesquisa. Sugira correções na base de dados, caso necessário;

#### Organizando dados

In [24]:
df_SatisfacaoCliente

,tipo_servico,canal_atendimento,faixa_etaria,tempo_espera,qualidade_percebida,preco_pago,atendimento_resolutivo,nps,tempo_resposta,isc
0,Intermediário,Telefone,26-35,"3,736380587","8,43922999","69,5023164",Sim,"9,147720663","2,423579217","61,65699228"
1,Básico,Presencial,51+,"10,00197234",10,"76,85151946",Sim,"4,317293738","2,990571694","48,98127783"
2,Básico,Telefone,36-50,"14,64158742","6,327451315","46,39094692",Sim,"7,118762214","2,183402259","42,71407099"
3,Premium,Telefone,36-50,"15,15167926","8,58274626","72,33233854",Não,"7,484347946","3,481049146","48,68741733"
4,Premium,E-mail,18-25,"15,16017515","5,226670323","40,13601188",Sim,"7,978081278","2,735962641","48,49573957"
...,...,...,...,...,...,...,...,...,...,...
1992,Premium,Telefone,36-50,"16,03682345","7,248273929","54,36453679",Sim,"3,203150785","1,908812102","45,67993717"
1993,Intermediário,Chat,18-25,"9,43248178","9,02726795","75,92082747",Sim,"9,208910411","3,216249292","58,99677999"
1994,Intermediário,E-mail,51+,"12,38164215","5,978571478","49,2845345",Sim,"7,616182885","1,356269948","44,70077572"
1995,Premium,Presencial,36-50,"10,46332168","8,2944781","67,65465996",Sim,"5,994454368","1,519053188","57,46931195"
1996,Intermediário,E-mail,51+,"11,88390975","4,630723998","35,32129366",Sim,"7,778618169","1,31203473","40,20186518"

In [25]:
# Passando numeros do formato brasileiro para o americano ("0,0" -> "0.0")

df_SatisfacaoCliente["tempo_espera"] = (df_SatisfacaoCliente["tempo_espera"].str.replace(",", ".", regex=False).astype(float))

df_SatisfacaoCliente["qualidade_percebida"] = (df_SatisfacaoCliente["qualidade_percebida"].str.replace(",", ".", regex=False).astype(float))

df_SatisfacaoCliente["preco_pago"] = (df_SatisfacaoCliente["preco_pago"].str.replace(",", ".", regex=False).astype(float))

df_SatisfacaoCliente["nps"] = (df_SatisfacaoCliente["nps"].str.replace(",", ".", regex=False).astype(float))

df_SatisfacaoCliente["tempo_resposta"] = (df_SatisfacaoCliente["tempo_resposta"].str.replace(",", ".", regex=False).astype(float))

df_SatisfacaoCliente["isc"] = (df_SatisfacaoCliente["isc"].str.replace(",", ".", regex=False).astype(float))

In [26]:
df_SatisfacaoCliente

,tipo_servico,canal_atendimento,faixa_etaria,tempo_espera,qualidade_percebida,preco_pago,atendimento_resolutivo,nps,tempo_resposta,isc
0,Intermediário,Telefone,26-35,3.736381,8.439230,69.502316,Sim,9.147721,2.423579,61.656992
1,Básico,Presencial,51+,10.001972,10.000000,76.851519,Sim,4.317294,2.990572,48.981278
2,Básico,Telefone,36-50,14.641587,6.327451,46.390947,Sim,7.118762,2.183402,42.714071
3,Premium,Telefone,36-50,15.151679,8.582746,72.332339,Não,7.484348,3.481049,48.687417
4,Premium,E-mail,18-25,15.160175,5.226670,40.136012,Sim,7.978081,2.735963,48.495740
...,...,...,...,...,...,...,...,...,...,...
1992,Premium,Telefone,36-50,16.036823,7.248274,54.364537,Sim,3.203151,1.908812,45.679937
1993,Intermediário,Chat,18-25,9.432482,9.027268,75.920827,Sim,9.208910,3.216249,58.996780
1994,Intermediário,E-mail,51+,12.381642,5.978571,49.284534,Sim,7.616183,1.356270,44.700776
1995,Premium,Presencial,36-50,10.463322,8.294478,67.654660,Sim,5.994454,1.519053,57.469312
1996,Intermediário,E-mail,51+,11.883910,4.630724,35.321294,Sim,7.778618,1.312035,40.201865

In [ ]:
#Passando variaveis quantitativas de string para float

df_SatisfacaoCliente.tempo_espera = pd.to_numeric(df_SatisfacaoCliente.tempo_espera, errors = 'coerce')
df_SatisfacaoCliente.qualidade_percebida = pd.to_numeric(df_SatisfacaoCliente.qualidade_percebida, errors = 'coerce')
df_SatisfacaoCliente.preco_pago= pd.to_numeric(df_SatisfacaoCliente.preco_pago, errors = 'coerce')
df_SatisfacaoCliente.nps = pd.to_numeric(df_SatisfacaoCliente.nps, errors = 'coerce')
df_SatisfacaoCliente.tempo_resposta = pd.to_numeric(df_SatisfacaoCliente.tempo_resposta, errors = 'coerce')
df_SatisfacaoCliente.isc = pd.to_numeric(df_SatisfacaoCliente.isc, errors = 'coerce')

In [28]:
df_SatisfacaoCliente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1997 entries, 0 to 1996
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   tipo_servico            1997 non-null   object
 1   canal_atendimento       1997 non-null   object
 2   faixa_etaria            1997 non-null   object
 3   tempo_espera            1987 non-null   float64
 4   qualidade_percebida     1987 non-null   float64
 5   preco_pago              1987 non-null   float64
 6   atendimento_resolutivo  1997 non-null   object
 7   nps                     1997 non-null   float64
 8   tempo_resposta          1997 non-null   float64
 9   isc                     1997 non-null   float64
dtypes: float64(6), object(4)
memory usage: 156.1+ KB

#### Verificando dados invalidos

In [36]:
categorias_validas_servico = ["Básico", "Intermediário","Premium"]
df_SatisfacaoCliente[~df_SatisfacaoCliente["tipo_servico"].isin(categorias_validas_servico)]

Empty DataFrame
Columns: [tipo_servico, canal_atendimento, faixa_etaria, tempo_espera, qualidade_percebida, preco_pago, atendimento_resolutivo, nps, tempo_resposta, isc]
Index: []

In [35]:
categorias_validas_canal = ["Telefone", "Chat", "E-mail", "Presencial"]
df_SatisfacaoCliente[~df_SatisfacaoCliente["canal_atendimento"].isin(categorias_validas_canal)]

Empty DataFrame
Columns: [tipo_servico, canal_atendimento, faixa_etaria, tempo_espera, qualidade_percebida, preco_pago, atendimento_resolutivo, nps, tempo_resposta, isc]
Index: []

In [37]:
categorias_validas_faixa_etaria = ["18-25", "26-35", "36-50", "51+"]
df_SatisfacaoCliente[~df_SatisfacaoCliente["faixa_etaria"].isin(categorias_validas_faixa_etaria)]

Empty DataFrame
Columns: [tipo_servico, canal_atendimento, faixa_etaria, tempo_espera, qualidade_percebida, preco_pago, atendimento_resolutivo, nps, tempo_resposta, isc]
Index: []

In [38]:
categorias_validas_atendimento_resolutivo = ["Sim", "Não"]
df_SatisfacaoCliente[~df_SatisfacaoCliente["atendimento_resolutivo"].isin(categorias_validas_atendimento_resolutivo)]

Empty DataFrame
Columns: [tipo_servico, canal_atendimento, faixa_etaria, tempo_espera, qualidade_percebida, preco_pago, atendimento_resolutivo, nps, tempo_resposta, isc]
Index: []

#### Verificando valores ausentes

In [33]:
df_SatisfacaoCliente.isna().sum()

tipo_servico               0
canal_atendimento          0
faixa_etaria               0
tempo_espera              10
qualidade_percebida       10
preco_pago                10
atendimento_resolutivo     0
nps                        0
tempo_resposta             0
isc                        0
dtype: int64

As variáveis tempo_espera, qualidade_recebida e atendimento_resolutivo possui 10 linhas com valores nulos

In [ ]:
#Linhas que possuem algum valor nulo
df_SatisfacaoCliente[df_SatisfacaoCliente.isna().any(axis=1)]

,tipo_servico,canal_atendimento,faixa_etaria,tempo_espera,qualidade_percebida,preco_pago,atendimento_resolutivo,nps,tempo_resposta,isc
88,Premium,E-mail,51+,7.489223,NaN,60.760175,Sim,5.546282,3.677717,55.393084
96,Básico,Chat,51+,10.093128,5.400201,NaN,Sim,6.866636,2.513074,46.238155
126,Intermediário,E-mail,18-25,9.219994,6.808065,NaN,Sim,8.554335,3.214775,53.141443
308,Básico,E-mail,26-35,14.811721,NaN,73.225919,Sim,2.123895,3.034310,53.039643
313,Intermediário,Presencial,51+,15.583499,NaN,61.382046,Sim,8.240459,4.039101,44.113812
325,Intermediário,Telefone,26-35,13.028801,6.894156,NaN,Não,8.833239,2.128514,50.119445
438,Intermediário,E-mail,36-50,NaN,8.047312,63.985907,Sim,8.657479,2.602805,44.782657
505,Intermediário,Presencial,18-25,NaN,5.102886,37.186398,Sim,2.843624,2.940033,36.965523
509,Intermediário,Telefone,18-25,11.207079,9.069495,NaN,Não,6.918051,2.883684,52.866904
514,Básico,Chat,36-50,16.186722,8.688969,NaN,Sim,4.194242,0.500000,41.569534
539,Intermediário,Telefone,26-35,8.952192,6.319750,NaN,Sim,9.175632,3.265200,46.712556
650,Básico,Telefone,26-35,12.972089,NaN,51.256754,Sim,6.723919,4.101310,34.108415
872,Básico,E-mail,36-50,11.766629,4.720120,NaN,Sim,7.198199,2.983473,43.988495
1128,Intermediário,Presencial,26-35,NaN,6.047911,48.386471,Não,7.159426,2.972633,47.337984
1220,Intermediário,E-mail,26-35,8.609866,NaN,54.285230,Não,8.646237,2.906336,49.397946
1263,Intermediário,Chat,26-35,NaN,6.521124,54.738321,Sim,6.228059,2.764579,54.688329
1282,Básico,Telefone,18-25,NaN,5.117138,44.031858,Sim,4.954471,2.234132,37.741546
1299,Básico,Telefone,26-35,NaN,7.762030,67.076417,Sim,6.195778,1.623673,51.829682
1372,Básico,Presencial,51+,NaN,8.784577,72.772290,Não,9.190710,2.714873,46.534573
1498,Básico,Chat,18-25,8.314527,10.000000,NaN,Sim,7.125927,1.975581,57.888113
1532,Premium,Chat,18-25,14.268319,NaN,58.992029,Sim,3.757058,3.732750,48.719299
1578,Intermediário,Telefone,26-35,NaN,2.229812,19.051070,Sim,6.304616,3.036951,42.620713
1582,Intermediário,Chat,36-50,NaN,4.227828,36.574693,Não,4.908287,3.246850,40.769731
1626,Básico,E-mail,36-50,11.612567,8.322003,NaN,Sim,8.847968,2.194886,54.520439
1636,Intermediário,Chat,26-35,12.807907,9.518927,NaN,Sim,8.032211,2.808264,43.683006
1702,Básico,Telefone,51+,8.641768,NaN,46.066297,Sim,5.076955,3.910256,42.033992
1732,Intermediário,Telefone,51+,NaN,6.026107,42.081565,Não,7.170772,2.196352,42.447422
1761,Intermediário,Presencial,36-50,9.672908,NaN,41.136962,Sim,7.781934,1.397844,45.481240
1795,Intermediário,E-mail,36-50,10.946692,NaN,61.501186,Sim,7.931363,2.795107,55.185132
1809,Básico,Telefone,51+,5.911062,NaN,61.639560,Sim,3.750292,3.056051,57.433654